### ISSUE TITLE
Not served over HTTPS

### ISSUE THREAD

**Issue by ghost** [PeARSearch/PeARSearch.github.io#6]
pearsearch.org is not currently served over [HTTPS](https://en.wikipedia.org/wiki/HTTP_Secure).

This is due to [GitHub bug #156: _Add HTTPS support to Github Pages including custom domains_](https://github.com/isaacs/github/issues/156).

The failure to use HTTPS puts visitors to the website at increased risk of various attacks. This might be less of a concern if pearsearch.org did not expect visitors to execute JavaScript, but [it does](https://github.com/PeARSearch/PeARSearch.github.io/issues/4).

Resolving #5 would potentially also resolve _this_ issue, by migrating pearsearch.org (and indeed the rest of the PeARS project's code hosting) off GitHub and onto a host that _does_ support HTTPS for custom domains.

Thanks!

**Comment by stultus** [comment]
Yes Yes.  Moving pearsearch.org into our own server is already in our TODO list :)

**Comment by ghost** [comment]
As an interim solution (i.e. not requiring the investment of time, attention and money required by self-hosting), you could still potentially solve this by resolving #5 :)

**Comment by minimalparts** [comment]
Sorry we're being slow with this -- most of PeARS team is currently either travelling or battling with urgent neural networks unrelated to PeARS ;) But yes, we have #5 on our discussion list for the next meeting. Thanks!

**Comment by stultus** [comment]
The site uses HTTPS now.
