### ISSUE TITLE
No license(s) specified

### ISSUE THREAD

**Issue by ghost** [PeARSearch/PeARSearch.github.io#7]
Some of the code in this repository appears not to be available under any license. Please could it be licensed under a [GPL-Compatible Free Software license](https://www.gnu.org/licenses/license-list.html)? I would suggest [AGPLv3](https://www.gnu.org/licenses/license-list.html#AGPLv3.0), so that people accessing forks/copies of the PeARS website over a network will automatically be entitled to the [Four Freedoms](https://en.wikipedia.org/w/index.php?title=Free_software&oldid=695656324#Definition_and_the_Four_Freedoms) in respect of any modifications that may have been made to those forks/copies.

Please could a [content license](https://www.gnu.org/licenses/license-list.html#OtherLicenses) also be specified? Ideally, please dual-license website content under [CC BY-SA 3.0](http://creativecommons.org/licenses/by-sa/3.0/) and GFDL, for compatibility/interoperability with the many projects using one or other (or both) of those licenses, such as [Wikipedia](https://wikimediafoundation.org/wiki/Terms_of_Use#7._Licensing_of_Content).

Thanks!

**Comment by stultus** [comment]
**TODO**  soon

**Comment by minimalparts** [comment]
@PeARSearch/all-pears could we possibly sort the license of the website, as requested by @sampablokuper? This issue has been lying around for a while...

The suggestions above sound good to me. But if anybody has other ideas, please share!

**Comment by stultus** [comment]
@minimalparts @nandajavarma , Let's go with AGPLv3.

**Comment by minimalparts** [comment]
Sounds good to me! Thanks for looking after this!

**Comment by stultus** [comment]
Done in 6857b73
